# Generated by Django 3.1.7 on 2022-09-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0003_aprendiz_fecha_nacimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=254)),
                ('rol', models.CharField(choices=[('R', 'Administrador'), ('I', 'Instructor'), ('A', 'Aprendiz')], default='A', max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='actividades',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='monitoria',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
