# Generated by Django 3.1.7 on 2022-09-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0004_auto_20220902_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
