# Generated by Django 3.1.7 on 2022-09-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0005_auto_20220902_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(default='territorio/fotos/perfil.png', upload_to='territorio/fotos'),
        ),
    ]
